version: "3"
services:
  admin:
    container_name: admin-app
    build: admin-app
    ports:
      - "4209:4200"
    volumes:
      - $PWD/admin-app:/app
    networks:
      custom_network:
        ipv4_address: 172.30.1.1
    depends_on:
      - backend
  backend:
    container_name: back-end
    build: back-end
    ports:
      - "3009:3000"
    volumes:
      - $PWD/back-end:/usr/src/app
    networks:
      custom_network:
        ipv4_address: 172.30.1.2
  client:
    container_name: client-site
    build: client-site
    ports:
      - "8089:8080"
    volumes:
      - $PWD/client-site:/app
    networks:
      custom_network:
        ipv4_address: 172.30.1.3
  deploy:
    container_name: user-tracking-deploy
    build: deploy
    environment:
      AWS_CONFIG_FILE: "/root/.aws/config"
    volumes:
      - ~/.aws/:/root/.aws/
      - ~/.ssh/:/root/.ssh/
      - $PWD:/code

networks:
  custom_network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
